############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5
    version: v5.9.6
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify
    version: v1.1.1
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-reveal
    version: v1.1.1
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind
    version: v1.1.1

# Mount directories to the site
mounts:
  - source: content
    target: content
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes

# Advanced Hugo module configuration
noVendor: true
proxy: direct
noMounts: false
